package io.diagrid.springai.durable.client;

import io.diagrid.springai.durable.workflow.AgentRequest;
import io.diagrid.springai.durable.workflow.AgentResult;
import io.dapr.workflows.client.DaprWorkflowClient;
import io.dapr.workflows.client.WorkflowFailureDetails;
import io.dapr.workflows.client.WorkflowRuntimeStatus;
import io.dapr.workflows.client.WorkflowState;
import java.time.Duration;
import java.util.concurrent.TimeoutException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Drives one durable {@code ChatClient} call: schedule the workflow under the given instance id,
 * block until it completes, and return the result.
 *
 * <p><b>Execution identity: dapr-agents parity.</b> Every call runs under a fresh
 * {@code UUID.randomUUID()} instance id (generated by the durable advisor), unless the caller supplies
 * their own. There is deliberately <b>no</b> reissue dedup or content-hash derivation: a retried or
 * duplicated call is a <em>new</em> execution, exactly as in Dapr Agents (Python). Client-retry
 * idempotency is the tool author's concern — make tool activities idempotent using the per-execution
 * {@code taskExecutionId} (see {@code ToolInvokeActivity}).
 *
 * <p>Two forms of recovery:
 * <ul>
 *   <li><b>Worker crash</b> — an in-flight workflow resumes from its history after a worker restart;
 *       completed activities are never re-executed. Intrinsic to durabletask; the blocking wait simply
 *       returns once a new worker finishes the instance.</li>
 *   <li><b>Wait-budget timeout</b> — if the call does not complete within the configured timeout, a
 *       {@link DurableCallTimeoutException} is thrown carrying the instance id. This is not a failure:
 *       the workflow keeps running to completion and can be inspected via Dapr tooling (the Diagrid
 *       dashboard, the {@code dapr workflow} CLI) using that id. The library intentionally exposes no
 *       in-app collect-by-id call — the id is for correlation.</li>
 * </ul>
 */
public class DurableRunner {

  private static final Logger LOG = LoggerFactory.getLogger(DurableRunner.class);

  private final DaprWorkflowClient client;
  private final Duration completionTimeout;

  public DurableRunner(DaprWorkflowClient client, Duration completionTimeout) {
    this.client = client;
    this.completionTimeout = completionTimeout;
  }

  /**
   * Schedules the request under {@code instanceId} and the given workflow name, then blocks until the
   * workflow completes and returns the {@link AgentResult} (final text plus aggregated response
   * metadata). The name lets a per-agent workflow (named after the ChatClient bean) be used instead of
   * the generic {@code AgentWorkflow.NAME}; it must be a name registered on the worker.
   *
   * @param instanceId   a unique instance id (the advisor supplies a random UUID, or a caller-chosen one)
   * @param request      the call rendered as workflow input
   * @param workflowName the workflow type to schedule (must be registered on the worker)
   * @throws DurableCallTimeoutException if the workflow does not complete within the configured
   *     timeout — it keeps running; inspect it via Dapr tooling using the instance id
   */
  public AgentResult run(String instanceId, AgentRequest request, String workflowName) {
    client.scheduleNewWorkflow(workflowName, request, instanceId);
    LOG.info("Scheduled durable workflow instance {} ({})", instanceId, workflowName);

    WorkflowState completed;
    try {
      completed = client.waitForWorkflowCompletion(instanceId, completionTimeout, true);
    } catch (TimeoutException e) {
      throw new DurableCallTimeoutException(instanceId, workflowName, e);
    }
    if (completed == null) {
      throw new IllegalStateException("No workflow instance found: " + instanceId);
    }
    return outputOrThrow(completed, instanceId);
  }

  /**
   * Returns the workflow output only when it genuinely COMPLETED. Any other terminal state (FAILED,
   * TERMINATED, CANCELED, …) has no valid output, so {@code readOutputAs} would return null/garbage;
   * surface it as an error carrying the backend failure details instead of masking the real failure.
   */
  static AgentResult outputOrThrow(WorkflowState state, String instanceId) {
    WorkflowRuntimeStatus status = state.getRuntimeStatus();
    if (status == WorkflowRuntimeStatus.COMPLETED) {
      return state.readOutputAs(AgentResult.class);
    }
    WorkflowFailureDetails failure = state.getFailureDetails();
    String detail =
        failure == null
            ? "no failure details"
            : failure.getErrorType() + ": " + failure.getErrorMessage();
    throw new IllegalStateException(
        "Durable workflow " + instanceId + " ended in status " + status + " (" + detail + ")");
  }
}
